### ISSUE TITLE
firefox addon 인 persnal-blocklist에서도 잘 막히네요.

### ISSUE THREAD

**Issue by ujuc** [RyuaNerin/only-stackoverflow#1]
https://addons.mozilla.org/en-US/firefox/addon/personal-blocklist/

<img width="655" alt="스크린샷 2020-06-23 21 26 48" src="https://user-images.githubusercontent.com/624975/85403510-6efdba80-b598-11ea-9c8a-05ef4b559c49.png">

혹시나 뒤지다가 나오는거 있으면 추가해놓겠습니다. :)

**Comment by RyuaNerin** [comment]
감사합니다.
