### ISSUE TITLE
차단 사이트 추가

### ISSUE THREAD

**Issue by hyuunnn** [RyuaNerin/only-stackoverflow#10]
https://github.com/Taraflex/Back2stackoverflow 도 같은 취지로 만들어진 repo로 보이는데 리스트 참고하면 좋을 것 같습니다.

그리고 새로운 사이트 제보합니다 (https://gotxt.net/)

**Comment by RyuaNerin** [comment]
적절히 추린 후에 적용해보겠습니다. 감사합니다.
