### ISSUE TITLE
adguard에서 작동 안함

### ISSUE THREAD

**Issue by green1052** [RyuaNerin/only-stackoverflow#16]
![K-001](https://user-images.githubusercontent.com/34261355/93017536-829f4700-f604-11ea-89fb-5d0cfb8108a0.png)

![K-002](https://user-images.githubusercontent.com/34261355/93017537-84690a80-f604-11ea-98b4-1d80ae096d6b.png)

안지워지네요

**Comment by RyuaNerin** [comment]
버전: `2020.09.12.17.43` 기준으로 정상적으로 작동을 확인했습니다.
![image](https://user-images.githubusercontent.com/6766851/93019534-8df96f00-f612-11ea-9ea2-0f791fb9ab1f.png)

<hr />

필터를 제거하신 후, 다시 추가하실 때 **신뢰함** 을 체크해주세요.
![image](https://user-images.githubusercontent.com/6766851/93019554-bbdeb380-f612-11ea-8703-b0c224880bd1.png)

이후에도 작동이 안되시면 해당 div 의 코드 혹은 페이지를 저장해서 [이메일](mailto://RyuaNerin<admin@ryuar.in>)로 보내주시면 다시 검토해보겠습니다.

**Comment by green1052** [comment]
메일 전송했습니다.

**Comment by RyuaNerin** [comment]
> 메일 전송했습니다.

시간나는 대로 최대한 빠르게 확인해보고 소식 전해드리겠습니다.

**Comment by green1052** [comment]
감사합니다

**Comment by RyuaNerin** [comment]
@green1052 파이어폭스에서 재현이 안되는데 혹시 Adguard 확장 플러그인이 아니라 OS 설치형을 사용하고 계신가요?

**Comment by green1052** [comment]
네 os 설치형 쓰고 있습니다.

**Comment by RyuaNerin** [comment]
Adguard Windows v7.5.1 에서 재현하지 못하였습니다.

**Comment by green1052** [comment]
음 일단 포기해야겠네요 신경 써주셔서 감사합니다.

**Comment by green1052** [comment]
그냥 pc 설치형에서 div를 필터링 못해서 그런거였네요;;
