### ISSUE TITLE
[Adblock Plus] 올바르지 않은 필터 리스트

### ISSUE THREAD

**Issue by hojongs** [RyuaNerin/only-stackoverflow#48]
![image](https://user-images.githubusercontent.com/15096588/125167093-c5588e00-e1d9-11eb-8278-b37c30598f23.png)

**Comment by hojongs** [comment]
현재 master branch의 commit인 e2f9f14 및 최근의 많은 커밋들에서도 모두 같은 이슈가 존재하고
3월로 거슬러올라가 3a6f89d 커밋에서는 잘 동작하는 것으로 보입니다

**Comment by RyuaNerin** [comment]
45ee0b76df273f70d12597f1ccfe7173bb3f8230 에서 수정하였습니다.

**Comment by hojongs** [comment]
이제 잘 되네요
감사합니다
