### ISSUE TITLE
Better way to block DDG results

### ISSUE THREAD

**Issue by iam-py-test** [RyuaNerin/only-stackoverflow#68]
I was looking at your filter, and I think there is a better way to block DuckDuckGo results (also expends support to Tor Browser):
```
duckduckgo.com,3g2upl4pq6kufc4m.onion,duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion##[data-domain$="domainidontlike.example"]
```
I don't have time right now to figure out how to make it work specifically for your filter, but hopefully this will help!

**Comment by RyuaNerin** [comment]
Thanks for your comment. I'll comment again after reviewing. 😄
