### ISSUE TITLE
검색결과 목록 내 숨겨진 항목들의 자리에 빈 공간이 생기는  문제

### ISSUE THREAD

**Issue by zvuc** [RyuaNerin/only-stackoverflow#71]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/2870726/147042145-d8dc072d-60f9-4092-bdea-d8540349bb66.png">

우선 좋은 필터 덕분에 잘 사용하고 있습니다 감사합니다. 👍 

크리티컬한 문제는 아니지만, 필터에 걸려 숨겨진 엘리먼트 상위 엘리먼트 (ul)에 패딩이 들어있어서 검색결과 항목간 빈 공간(갭)이 크게 떠보이는 문제가 있습니다. 타겟팅 필터 조건을 상위 엘리먼트까지 포함하게 만들어 갭을 없앨 수 있으면 더 깔끔할 것 같습니다.

사용환경은 Safari/Firefox용 AdGuard입니다. 양쪽다 동일하게 나타납니다.

모든 경우에 다 이런건 아니고,
<img width="888" alt="Pasted_Image_2021_12_22_14_51" src="https://user-images.githubusercontent.com/2870726/147042438-12f11dd9-0118-4f03-b606-a732a0ae75fb.png">
이런식으로 동일 사이트내 하위 검색결과가 트리 형태로 나타나는 식에만 ul li 형태의 껍데기가 추가로 붙어서 생기는 문제가 아닐까 싶기도 합니다.

**Comment by RyuaNerin** [comment]
반영하였습니다.
![image](https://user-images.githubusercontent.com/6766851/147044333-3f5f37e4-4592-4e5b-875a-7e23e4640455.png)
