### ISSUE TITLE
Replace spam links with real stackoverflow results

### ISSUE THREAD

**Issue by Atemu** [RyuaNerin/only-stackoverflow#72]
Hi, glad to see I'm not the only one annoyed by these spam sites. Would it be possible to, instead of removing the links all together, replace them with the real stackoverflow links?

Some consideration may have to be put towards deduplicating results.

**Comment by RyuaNerin** [comment]
Hello. Thank you for the new idea.

First, Adblock Plus rules doesn't support the replacement syntax.

I think it can be implemented with [`$replace Syntax`](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier) of rules extended of Adguard.
But i want to maintain compatibility between plugins, so i don't want to add it.

Thanks.

**Comment by CennoxX** [comment]
@Atemu There are other projects that do that, like https://github.com/vladgba/Back2source/.

**Comment by Atemu** [comment]
Thanks, I'll take a look
