### ISSUE TITLE
Output for ublacklist

### ISSUE THREAD

**Issue by item4** [RyuaNerin/only-stackoverflow#90]
[ublacklist](https://github.com/iorate/ublacklist) supports remove blocked sites from search result.

**Comment by xnuk** [comment]
Did you know there is [/ublacklist.txt](/ublacklist.txt), and similar project called [arosh/ublacklist-stackoverflow-translation](https://github.com/arosh/ublacklist-stackoverflow-translation)?

**Comment by xnuk** [comment]
Related: https://github.com/arosh/ublacklist-stackoverflow-translation/issues/165

**Comment by RyuaNerin** [comment]
Hello. Sorry for the delay.

You can use only-stackoverflow by adding [/ublocklist.txt](/ublacklist.txt) to ublocklist
`https://raw.githubusercontent.com/RyuaNerin/only-stackoverflow/master/ublacklist.txt`
