### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by dveamer** [RyuaNerin/only-stackoverflow#92]
I can not access your subscribe page (subscribe.adblock.org).
I tried to acceess it from two devices.

It is probably a domain issue. 
Error message is DNS_PROBE_FINISHED_NXDOMAIN

https://subscribe.adblockplus.org/?location=https://github.com/RyuaNerin/only-stackoverflow/raw/master/only-stackoverflow.txt&title=only-stackoverflow

**Comment by sh-cho** [comment]
I'm using AdGuard and can reproduce it.

https://adblockplus.org/subscriptions

Via subscription link in this page, subscription is working. But if I manually copy link and access, it's not working.

**Comment by dveamer** [comment]
Adblock 확장앱을 설치 후 링크를 누르니 필터가 등록이 되네요. 저는 구독하는 방법 적힌 가이드 패이지가 보일 줄 알았어요.

좋은 필터 제공해주셔서 고맙습니다.
이슈는 닫도록 하겠습니다.
