### ISSUE TITLE
[질문] hosts.txt 가 업데이트 됐을 때 only-stackoverflow 필터 구독자들에게 모두 업데이트되나요?

### ISSUE THREAD

**Issue by TayPark** [RyuaNerin/only-stackoverflow#94]
`hosts.txt` 파일이 수정됐다면 기존 필터 구독자들에게 신규 필터(업데이트된 hosts.txt)가 적용되는지 궁금합니다. 

[오늘 있었던 업데이트](https://github.com/RyuaNerin/only-stackoverflow/pull/93) 의 업데이트 시간과 기존에 필터를 구독했던 시간의 오차가 커서(N days ago) 여쭤봅니다.

만약 그렇지 않다면, FAQ 에 해당 항목을 포함하여 알아두면 좋은 것들을 명시해두는게 좋을거 같습니다.

참고로 저는 Adblock 을 쓰고있습니다.

감사합니다.

**Comment by RyuaNerin** [comment]
안녕하세요.

only-stackoverflow는 필터 구독을 위해서 github repository에서 직접 hosts.txt 파일을 가져오는 방식으로 이루어져 있습니다.
다만, github에서 파일을 제공할 때 항상 최신 데이터를 전해주는 것이 아니라, 내부 캐시를 사용하기 때문에 업데이트 다소 지연될 수 있습니다.

**Comment by TayPark** [comment]
감사합니다!
